[package]
name = "ocdx-launcher"
version = "0.2.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
name = "ocdx_launcher"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "ocdx"
path = "src/main.rs"

[dependencies]
asar = "=0.3.0"
dirs = "=6.0.0"
electron-hook = { git = "https://github.com/Hona/Electron-Hook.git", rev = "04c070a9a4d3aecc073458138d46c079284b1880" }
serde_json = "=1.0.150"

[target.'cfg(windows)'.dependencies]
electron-hook-detours-sys = "=0.1.0"
winapi = { version = "0.3.9", features = [
  "errhandlingapi",
  "fileapi",
  "handleapi",
  "libloaderapi",
  "processthreadsapi",
  "synchapi",
  "winbase",
] }

[target.'cfg(windows)'.build-dependencies]
winresource = { version = "=0.1.19", default-features = false }
